# helm -n kafka upgrade --install --values k8s/kafka/values/36/nodeport-values.yaml velokafka361  oci://registry-1.docker.io/bitnamicharts/kafka
service:
  type: NodePort
  ports:
    client: 30109
    internal: 9093
  nodePorts:
    client: "30109"
rbac:
  create: true
externalAccess:
  enabled: false 
  autoDiscovery:
    enabled: true

controller:
  replicaCount: 1

listeners:
  client:
    containerPort: 30109
    protocol: PLAINTEXT
    name: CLIENT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT
    sslClientAuth: ""

  #advertisedListeners: "INTERNAL://$(MY_POD_NAME).velokafka361-controller-headless.kafka.svc.cluster.local:9093,CLIENT://velokafka.westus2.cloudapp.azure.com:30109"
  advertisedListeners: "CLIENT://velokafka.westus2.cloudapp.azure.com:30109,INTERNAL://velokafka361-controller-0.velokafka361-controller-headless.kafka.svc.cluster.local:9094" 

deleteTopicEnable: true
