---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-planes50
  namespace: simulators
  labels:
    app: send-planes50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-planes50
  template:
    metadata:
      labels:
        app: send-planes50
    spec:
      containers:
        - name: send-planes50
          image: david62243/rttest-send:230923
          command: ["/opt/rttest/sendKafka", "-b", "velokafka1.default:9092", "-t", "planes50", "-f", "/data/planes", "-r", "50", "-n", "-1"]
          #command: ["sleep", "3650d"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '500m'
              memory: 1Gi
            requests:
              cpu: '500m'
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rttest-send