---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-planes1x50
  namespace: rttest-send
  labels:
    app: send-planes1x50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-planes1x50
  template:
    metadata:
      labels:
        app: send-planes1x50
    spec:
      containers:
        - name: send-planes1x50
          image: david62243/rttest-send:231016
          command: ["/opt/rttest/sendKafka", "-b", "velokafka1-headless.kafka:9093", "-t", "planes1x50", "-f", "/data/planes", "-r", "50", "-n", "-1"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '250m'
              memory: 1Gi
            requests:
              cpu: '250m'
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rttest-send