rbac:
  create: true
externalAccess:
  enabled: true 
  autoDiscovery:
    enabled: true
auth:
  clientProtocol: sasl
  sasl:
    jaas:
      clientUsers:
        - user
        - david
      clientPasswords:
        - someBIGpasswordThatNobodyWouldGuess
        - password1
