# docker build -t david62243/rttest-send:231228 -f docker/Dockerfile-rttest-send-multistage .

#
# Build stage
#

FROM maven:3.8.5-openjdk-17-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml install

#
# Package stage
#

FROM openjdk:22-ea-17-slim

COPY ./target/lib /opt/rttest/target/lib
COPY ./target/rttest.jar /opt/rttest/target/rttest.jar
COPY planes.csv /opt/rttest/planes.csv
COPY planes.json /opt/rttest/planes.json
COPY planes.tab /opt/rttest/planes.tab
COPY mon* /opt/rttest/
COPY send* /opt/rttest/
COPY sink* /opt/rttest/

WORKDIR /opt/rttest