# docker build -t david62243/rttest-mon:20210406 -f docker/Dockerfile-rttest-mon .
FROM centos:8.3.2011

RUN yum install -y java-11-openjdk vim tmux

COPY target/lib /opt/rttest/target/lib
COPY target/rttest.jar /opt/rttest/target/rttest.jar
COPY mon* /opt/rttest/
COPY send* /opt/rttest/
COPY sink* /opt/rttest/

WORKDIR /opt/rttest
