FROM centos:7.6.1810

RUN yum install -y java-1.8.0-openjdk vim tmux

COPY target/lib /opt/rttest/target/lib
COPY target/rttest.jar /opt/rttest/target/rttest.jar
COPY planes.csv /opt/rttest/planes.csv
COPY planes.json /opt/rttest/planes.json
COPY planes00000 /opt/rttest/planes00000
COPY planes00001 /opt/rttest/planes00001
COPY Flight.csv /opt/rttest/Flight.csv
COPY sendPlanes /opt/rttest/sendPlanes
