# helm -n kafka upgrade --install --values k8s/kafka/values/33/nodeport-sasl-tls-values.yaml velokafka4 k8s/kafka/helm/kafka
service:
  type: NodePort
  ports:
    client: 30006
    internal: 6093
  nodePorts:
    client: "30006"
rbac:
  create: true
externalAccess:
  enabled: false 
  autoDiscovery:
    enabled: true
auth:
  clientProtocol: sasl_tls
  tls:
    pemChainIncluded: true
    type: pem
    existingSecrets:
    - kafka-tls
  sasl:
    jaas:
      clientUsers:
        - user
        - david
      clientPasswords:
        - LongPasswordHere
        - DiffcultToGuess

advertisedListeners: "INTERNAL://$(MY_POD_NAME).velokafka4-headless.kafka.svc.cluster.local:6093,CLIENT://velokafka.westus2.cloudapp.azure.com:30006"