apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  labels:
    app: mosquitto
data:
  password.txt: |
    david:$7$101$4n1Qzlq2BnwdZELY$6KTf9VMdXC6U5qlhRoVcw4qZl1ZqCWccFevqmkn/6d61QCDN0s5QT6CjXgdoxhOm1Lw28ANcc0QhJdrNlvHGpQ==